spring:
  application:
    name: coding-assessment-platform

  datasource:
    url: jdbc:postgresql://localhost:5432/coding_assessment
    username: divyakshchachan
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: 5b3f8b9a7d2e1c4f6a8b0d9e3f7a1c5e8b2d4f6a9c1e3b5d7f8a0c2e4b6d8f1a
  expiration: 3600000
server:
  port: 8080