spring:
  application:
    name: coding-assessment-platform

  datasource:
    url: jdbc:postgresql://localhost:5432/coding_assessment
    username: divyakshchachan
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: 6VLA2RNDneB+WkcmM92+8qohHbNpv37YEC1uDHs08pI=
  expiration: 3600000
server:
  port: 8080